#!/usr/bin/env python3
"""mora-slop — Catalog Generator

Scans skills/ directory, extracts YAML frontmatter, and produces catalog.yaml.

Usage: python3 scripts/generate-catalog.py > catalog.yaml
"""

import os
import sys
import re
from datetime import date


def extract_frontmatter(filepath):
    """Extract YAML frontmatter from a markdown file."""
    with open(filepath, 'r') as f:
        content = f.read()

    match = re.match(r'^---\n(.*?)\n---', content, re.DOTALL)
    if not match:
        return None

    frontmatter = {}
    for line in match.group(1).split('\n'):
        if ':' in line:
            key, _, value = line.partition(':')
            key = key.strip()
            value = value.strip().strip('"').strip("'")

            # Handle arrays
            if value.startswith('[') and value.endswith(']'):
                value = [v.strip().strip('"').strip("'")
                         for v in value[1:-1].split(',')]

            frontmatter[key] = value

    return frontmatter


def format_tags(tags):
    """Format tags as YAML array."""
    if isinstance(tags, list):
        return '[' + ', '.join(tags) + ']'
    return tags


def main():
    skills_dir = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), '..', 'skills')
    schemas_dir = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), '..', 'schemas')

    print("# mora-slop — Skill Catalog")
    print("# Auto-generated by scripts/generate-catalog.py")
    print("# Run: python3 scripts/generate-catalog.py > catalog.yaml")
    print("#")
    print("# This file is machine-readable so Claude can search and recommend skills.")
    print()
    print(f'version: "1.0"')
    print(f'last_updated: "{date.today().isoformat()}"')
    print()
    print("skills:")

    for filename in sorted(os.listdir(skills_dir)):
        if not filename.endswith('.md') or filename == 'SKILL-TEMPLATE.md':
            continue

        filepath = os.path.join(skills_dir, filename)
        fm = extract_frontmatter(filepath)
        if not fm:
            print(f"  # SKIPPED: {filename} — no frontmatter", file=sys.stderr)
            continue

        name = fm.get('name', filename[:-3])
        print(f"  - name: {name}")
        print(f"    path: skills/{filename}")
        print(f"    tags: {format_tags(fm.get('tags', []))}")
        print(f'    trigger: "{fm.get("trigger", "TODO")}"')
        print(f"    author: {fm.get('author', 'unknown')}")
        print(f'    version: "{fm.get("version", "1.0")}"')
        if 'estimated_time_saved' in fm:
            print(f'    estimated_time_saved: "{fm["estimated_time_saved"]}"')
        print()

    # Schemas
    print("schemas:")
    for filename in sorted(os.listdir(schemas_dir)):
        if not filename.endswith('.yaml'):
            continue
        filepath = os.path.join(schemas_dir, filename)
        with open(filepath, 'r') as f:
            first_line = f.readline().strip()
        desc = first_line.lstrip('# ').split('—')[-1].strip() if '—' in first_line else filename
        name = filename[:-5]
        print(f"  - name: {name}")
        print(f"    path: schemas/{filename}")
        print(f'    description: "{desc}"')
        print()


if __name__ == '__main__':
    main()
